### ISSUE TITLE
TypeError: list indices must be integer or slices,  not str

### ISSUE THREAD

**Issue by shsur-27** [mhiyer/coco-annotations-to-xml#1]
Traceback (most recent call last):
File "annotations_to_xml.py", line 103, in <module>
annotations = doc['annotations']
TypeError: list indices must be integers or slices, not str

I am facing this problem while converting coco annotations to xml format

**Comment by PiotrG1996** [comment]
> Traceback (most recent call last): File "annotations_to_xml.py", line 103, in annotations = doc['annotations'] TypeError: list indices must be integers or slices, not str
> 
> I am facing this problem while converting coco annotations to xml format

Have you found a solution to this issue?
